#!/bin/bash
# shellcheck disable=SC1091,SC2013,SC2153,SC2002,SC2126,SC2010,SC2206

# Christmas 2024 somewere in Greece...
# Merry Christmas

# GNU General Public License v2.0
# For more information, please refer <https://github.com/rizitis/apk/blob/main/LICENSE>

# Check if running as root
if [[ "$EUID" -ne 0 ]]; then
    echo "apk is a package manager! A package manager must be run as root. Exiting." >&2
    exit 1
fi

# source env
. /etc/apk/apk.env

# home dir
saved_dir=$(pwd)

# Extract the command argument
command=$1
PKG=$2

# List of commands that do not accept $2
invalid_with_second_arg="update|upgrade|restore-apk|upgrade-apk|info|stats|help|--help|-h"

# Check if $1 matches any command in the list
if [[ "$1" =~ $invalid_with_second_arg ]]; then
    if [[ -n "$2" ]]; then
        echo "Error: Command '$1' does not accept a second argument."
        echo "Please command <apk help> for help."
        exit 1
    fi
fi

must_have_second_arg="add|del|search|fix|download|show"

if [[ "$1" =~ $must_have_second_arg && -z "$2" ]]; then
    echo "Error: Command '$1' must be followed by a package_name." >&2
    echo "Please use 'apk help' for assistance." >&2
    exit 1
fi


if [[ "$1" == "--help" || "$1" == "-h" || "$1" == "help" ]]; then
    echo "
    # === Commands for  Download,Install,Upgrade,Remove,Search <packages> === #
    #
    # apk add pkg       Add/Install a package and its dependencies if exist in apk repository
    # apk del pkg       Delete a package
    # apk search pkg    Search for packages
    # apk show pkg      Print information about a package
    # apk fix pkg       Repair package or Upgrade it without modifying dependencies
    # apk download pkg  Download package files but not install
    #
    # === Commands which not followed by <package> === #
    #
    # apk update        Update apk repository {local files and package list}.
    # apk upgrade       Upgrade all installed packages from the apk repository ONLY.
    # apk info          List all installed packages from the apk repository ONLY.
    # apk stats         Show statistics ONLY about apk repository and installations.
    # apk upgrade-apk   Upgrade apk script version and apk.env.
    # apk restore-apk   downgrade apk script and apk.env to previous status before upgrade-apk.
    # apk help          Print help message
    "
else
    # Check if at least one argument is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <command> [<package>]"
    echo "Commands: fix, show, add, download, search, upgrade, del, update, info, stats, upgrade-apk, restore-apk, help"
    echo '
    # apk update        Update apk repository local files and package list
    # apk upgrade       Upgrade all installed pkg from apk repository
    # apk add pkg       Add/Install a package
    # apk del pkg       Delete a package
    # apk search pkg    Search for packages
    # apk show pkg      Print information about a package
    # apk info          List all installed packages
    # apk fix           Repair (Reinstall) a package or Install/Upgrade it without modifying dependencies
    # apk stats         Show statistics about repositories and installations
    # apk download pkg  Download package files but not install
    # apk upgrade-apk   Upgrade apk version
    # apk restore-apk   downgrade apk one version back
    # apk help          Print help message
    '
    exit 1
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

shift

# Handle commands
case $command in
    fix)
        echo "Fixing package..."
        temp_dir=$(mktemp -d)
        if [ ! -d "$temp_dir" ]; then
        echo "Failed to create temporary directory"
        exit 1
        fi
        cd "$temp_dir" || exit

        curl -L -O "$RF"/"$PKG"/BIN_NAME || { echo "Failed to download BIN_NAME"; exit 1; }
        FN="$(cat BIN_NAME)"
        echo "$FN"
        for file in "$FN" "$FN".md5; do
        curl -L -O "$RF"/"$PKG"/"$file"
        done

        expected_checksum=$(cut -d ' ' -f 1 "$FN".md5)
        # Compute the checksum of the downloaded file
        computed_checksum=$(md5sum "$FN" | cut -d ' ' -f 1)
        # Compare the checksums
        if [ "$expected_checksum" = "$computed_checksum" ]; then
        echo "Validation successful: Checksums match."
        else
        echo "Validation failed: Checksums do not match!"
        exit 1
        fi

        upgradepkg --install-new --reinstall "$FN"

        cd "$saved_dir" || exit
        rm -rf "$temp_dir"
        ;;
    show)
        echo -e "${BLUE}Showing package info...${NC}"
        temp_dir=$(mktemp -d)
        if [ ! -d "$temp_dir" ]; then
        echo -e "${RED}Failed to create temporary directory.${NC}"
        exit 1
        fi
        cd "$temp_dir" || exit

        echo -e "${BLUE}Attempting to download package info for '${YELLOW}$PKG${BLUE}'...${NC}"
        if ! curl -L --fail -O "$RF/$PKG/BIN_NAME"; then
        echo -e "${RED}Error: Package '${YELLOW}$PKG${RED}' does not exist in the appstream repository.${NC}" >&2
        echo -e "${YELLOW}Please check the package name or try a different repository.${NC}" >&2
        rm -rf "$temp_dir"
        exit 1
        fi

        FN="$(cat BIN_NAME)"
        echo -e "${GREEN}Package information successfully retrieved.${NC}"
        for file in "$FN".txt makepkg-"$PKG".log "$PKG".dep; do
        echo -e "${BLUE}Attempting to download ${YELLOW}$file${BLUE}...${NC}"
        if curl -L --fail -O "$RF/$PKG/$file"; then
        echo -e "${GREEN}Downloaded $file successfully.${NC}"
        else
        echo -e "${YELLOW}File $file does not exist or failed to download. Skipping.${NC}"
        fi
        done

        for file in "$FN".txt makepkg-"$PKG".log; do
        if [ -f "$file" ]; then
        echo -e "${BLUE}Contents of $file:${NC}"
        cat "$file"
        else
        echo -e "${YELLOW}File $file does not exist.${NC}"
        fi
        done

        if [ -f "$PKG".dep ]; then
        echo -e "${BLUE}Dependencies:${NC}"
        cat "$PKG".dep
        else
        echo -e "${YELLOW}No dependencies found for $PKG.${NC}"
        fi

        cd "$saved_dir" || exit
        rm -rf "$temp_dir"
        ;;
    add)
        temp_dir=$(mktemp -d)
        if [ ! -d "$temp_dir" ]; then
        echo "Failed to create temporary directory"
        exit 1
        fi

        cd "$temp_dir" || exit

        # Download BIN_NAME and extract the filename
        curl -L -O "$RF"/"$PKG"/BIN_NAME || { echo "Failed to download BIN_NAME"; exit 1; }
        FN="$(cat BIN_NAME)"

        # Download related files: main file, checksum, and dependencies
        for file in "$FN" "$FN".md5 "$PKG".dep; do
        if curl -L --fail -O "$RF"/"$PKG"/"$file"; then
        echo "Downloaded $file successfully."
        else
        echo "File $file does not exist or failed to download. Skipping."
        fi
        done

        # Check for dependencies and install them
        if [ -f "$PKG.dep" ]; then
        echo "Dependencies found:"
        cat "$PKG".dep
        for dep in $(cat "$PKG".dep); do
        echo "Installing dependency: $dep"
        apk add "$dep" || true  # Continue even if a dependency fails or not exist in repository
        done
        else
        echo "No dependencies found for $PKG."
        fi

        # Validate checksum
        if [ -f "$FN".md5 ]; then
        expected_checksum=$(cut -d ' ' -f 1 "$FN".md5)
        computed_checksum=$(md5sum "$FN" | cut -d ' ' -f 1)

        if [ "$expected_checksum" = "$computed_checksum" ]; then
        echo "Validation successful: Checksums match."
        else
        echo "Validation failed: Checksums do not match!"
        exit 1
        fi
        else
        echo "Checksum file $FN.md5 not found. Skipping validation."
        fi

        # Finally Upgrade package
        echo "Upgrading package using: $FN"
        upgradepkg --install-new --reinstall "$FN"

        # Clean up
        cd "$saved_dir" || exit
        rm -rf "$temp_dir"
        ;;
    download)
        if [ -d /tmp/"$PKG" ]; then
        mv /tmp/"$PKG" /tmp/"$PKG".bak
        fi
        mkdir -p /tmp/"$PKG"
        cd /tmp/"$PKG" || exit
        echo "Downloading $PKG files"
        curl -L -O "$RF"/"$PKG"/BIN_NAME || { echo "Failed to download BIN_NAME"; exit 1; }
        FN="$(cat BIN_NAME)"
        echo "$FN"
        for file in "$FN" "$FN".txt makepkg-"$PKG".log "$PKG".dep "$FN".md5; do
        if curl -L --fail -O "$RF"/"$PKG"/"$file"; then
        echo "Downloaded $file successfully."
        else
        echo "File $file does not exist or failed to download. Skipping."
        fi
        done
        pwd
        ls
        ;;
    search)
        # Create a temporary directory
        temp_dir=$(mktemp -d)
        if [ ! -d "$temp_dir" ]; then
        echo -e "${RED}Failed to create temporary directory.${NC}"
        exit 1
        fi

        cd "$temp_dir" || exit
        surl="$RF/$PKG/BIN_NAME"

        # Use curl to download the file and print its contents
        echo -e "${BLUE}Checking if file exists in apk repo...${NC}"
        if curl -L --silent --fail "$surl"; then
        echo -e "${GREEN}File exists in apk repo:${NC}"
        curl -L --silent "$surl"  # Print the file's contents
        else
        echo -e "${RED}File does not exist in apk repo.${NC}"
        fi

        echo ""
        echo -e "${BLUE}Searching if package exists in installed apk packages...${NC}"
        if cat "$_FDATA" | grep "$PKG"; then
        echo -e "${GREEN}Package found in installed packages.${NC}"
        else
        echo -e "${YELLOW}Package not found in installed packages.${NC}"
        fi

        # Clean up
        cd "$saved_dir" || exit
        rm -rf "$temp_dir"
        ;;
    upgrade)
        echo "(apk upgrade) upgrade packages only from apk repo."
        apk update
        PAK=$(sed 's/-[0-9]\+.*//' $_FDATA)
        for up in $PAK; do
        apk fix "$up" || true
        done
        ;;
    del)
        cd /var/adm/packages || exit
        RPKG=$(ls | grep "$PKG" | grep _rtz)
        # Check if any packages were found
        if [[ -z "$RPKG" ]]; then
        echo -e "${RED}No packages found${RESET}"
        exit 1
        fi


        echo -e "${BLUE}Packages found, Please confirm to delete:${RESET}"

        RPKG_ARRAY=($RPKG)
        counter=1
        for package in "${RPKG_ARRAY[@]}"; do
        echo -e "${YELLOW}$counter) $package${RESET}"
        ((counter++))
        done

        echo -e "${YELLOW}Please select the package by number to delete or press 0 to cancel:${RESET}"
        read -p "Your choice: " choice

        if [[ "$choice" -eq 0 ]]; then
        echo -e "${RED}Operation canceled.${RESET}"
        exit 0
        elif [[ "$choice" -gt 0 && "$choice" -le "${#RPKG_ARRAY[@]}" ]]; then
        # If valid choice, confirm and proceed to delete
        selected_package="${RPKG_ARRAY[$choice-1]}"
        echo -e "${GREEN}You selected: $selected_package${RESET}"
        read -p "Are you sure you want to delete $selected_package? (y/n): " confirmation

        if [[ "$confirmation" == "y" || "$confirmation" == "Y" ]]; then
        echo -e "${BLUE}Deleting $selected_package...${RESET}"
        removepkg "$selected_package"
        echo -e "${GREEN}Package $selected_package has been deleted.${RESET}"
        else
        echo -e "${RED}Deletion canceled.${RESET}"
        fi
        else
        echo -e "${RED}Invalid selection, please choose a valid number.${RESET}"
        exit 1
        fi
        ;;
    update)
    echo "Updating repository list..."
    # Check if the file list exists
    if [ -f "$_DSHARE"/"$_FLIST" ]; then
        LISTNUM=$(cat "$_DSHARE"/"$_FLIST")
        if [[ "$LISTNUM" == 0 ]]; then
        echo "This is the second time you run apk update ;)."
        # Backup and update the file list
        cd "$_DSHARE" || exit
        mv "$_FLIST" "$_FLIST".bak
        curl -L -O "$RF"/"$FLIST"
        mv "$FLIST" "$_FLIST"
        cd "$saved_dir" || exit
        echo "$_FLIST Updated! used: plan1"
        else
        [ "$LISTNUM" != 0 ]
        echo "Updating $_FLIST ..."
        # Backup and update the file list
        cd "$_DSHARE" || exit
        mv "$_FLIST" "$_FLIST".bak
        curl -L -O "$RF"/"$FLIST"
        mv "$FLIST" "$_FLIST"
        cd "$saved_dir" || exit
        echo "$_FLIST Updated! used: plan2"
        fi

    else
        if [ -f "$_DSHARE/$_FLIST.bak" ] && [ ! -f "$_DSHARE/$_FLIST.bak" ]; then
        echo "$_DSHARE/$_FLIST does not exist!"
        echo "However, a backup $_FLIST.bak exists..."
        echo "Attempting to fix this issue by using the back-up $_FLIST..."
        cd "$_DSHARE" || exit
        mv "$_FLIST".bak "$_FLIST"
        cd "$saved_dir" || exit
        echo "You are now using the back up file, used: plan-restore"
        echo "Please run one more time <apk update>"
        echo "Tips: check your internet connection, check your users permissions are you root?"
        else
        echo "$_DSHARE/$_FLIST or $_DSHARE/$_FLIST.bak not found. Creating directory and files..."
        # Create the file list
        mkdir -p "$_DSHARE"
        cd "$_DSHARE" || exit
        curl -L -O "$RF"/"$FLIST0"
        mv "$FLIST0" "$_FLIST"
        cd "$saved_dir" || exit
        echo "$_FLIST created successfully!"
        echo "Please run one more time <apk update> to complete set-up! used: plan 0"
        fi

    fi

    # Check if FDATA exists
    if [ -f "$_FDATA" ]; then
        echo "$_FDATA found..."
        echo "Updating $_FDATA ..."
        ls /var/adm/packages/ | grep "_rtz" > "$_FDATA"
    else
        echo "Package data file ($_FDATA) not found."
        echo "Creating $_FDATA with 0 packages in."
        mkdir -p "$_DDATA"
        cd "$_DDATA" || exit
        curl -L -O "$RF/$FDATA"
        cd "$saved_dir" || exit
        echo "$_FDATA created successfully!"
    fi
    ;;
    info)
       if [ -f "$_FDATA" ]; then
       FDATA_NUM=$(cat "$_FDATA")
            if [[ "$FDATA_NUM" == 0 ]]; then
            echo "No apk packages are installed so far!"
            else
            echo "Listing apk installed packages..."
            cat "$_FDATA"
            fi
        else
        echo "$_FDATA not found."
        echo "Try <apk update> to fix this."
        echo "If you already did, please open an issue in $MAIN_REPO/issues"
        fi
        ;;
    stats)
        echo -e "\033[1;34mFirst updating apk files...\033[0m"
        apk update
        echo ""
        echo -e "\033[1;32mReady! Displaying apk statistics...\033[0m"
        echo ""

        echo -e "\033[1;36mRepository URL:\033[0m \033[4m$MAIN_REPO\033[0m"
        echo ""

        if [[ -f "$_FDATA" ]]; then
        # Count the number of lines
        lines=$(wc -l < "$_FDATA")
        echo -e "\033[1;32mYou have already installed \033[1;33m$lines\033[1;32m apk packages.\033[0m"
        else
        echo -e "\033[1;31mFile $_FDATA does not exist. Run: apk update first.\033[0m"
        fi
        echo ""

        if [[ -f "$_DSHARE"/"$_FLIST" ]]; then
        # Count the number of lines
        lines=$(grep -v '^\s*#' "$_DSHARE/$_FLIST" | grep -v '^\s*$' | wc -l)
        echo -e "\033[1;32mapk repository currently has \033[1;33m$lines\033[1;32m packages ready for installation.\033[0m"
        else
        echo -e "\033[1;31mFile $_FLIST does not exist. Run: apk update first.\033[0m"
        fi
        echo ""

        echo -e "\033[1;36mapk package manager last update appstream was:\033[0m"
        echo -e "\033[1;33m$(curl -s "https://api.github.com/repos/rizitis/apk/commits?path=apk" | jq -r '.[0].commit.committer.date')\033[0m"
        echo ""

        echo -e "\033[1;36mYour apk script was updated locally:\033[0m"
        stat /usr/local/sbin/apk | grep "Modify:"
        echo ""

        echo -e "\033[1;36mTo upgrade apk to a new version (if needed):\033[0m"
        echo -e "\033[1;33mcommand: apk upgrade-apk\033[0m"
        echo ""

        echo -e "\033[1;36mTo report a bug:\033[0m \033[4m$MAIN_REPO/issues\033[0m"
        echo -e "\033[1;36mCurrently open issues number is:\033[0m \033[1;33m$(curl -s "https://api.github.com/repos/rizitis/apk/issues?state=open" | jq length)\033[0m"
    ;;
    upgrade-apk)
        echo "Taking backup $_FENV"
        if [ -f "$_FENV".back ]; then
        cat "$_FENV" > "$_FENV".back
        else
        cp "$_FENV" "$_FENV".back
        fi
        echo "Taking backup $_APK"
        if [ -f "$_APK".back ]; then
        cat "$_APK" > "$_APK".back
        chmod -x "$_APK".back
        else
        cp "$_APK" "$_APK".back
        chmod -x "$_APK".back
        fi
        echo "Upgrading $_APK"
        pushd "$_DAPK" || exit
        rm "$_APK" || exit
        curl -L -O "$RF"/"$APK"
        chmod +x "$_APK"
        echo "Upgrading $_FENV"
        cd "$_DETC" || exit
        rm "$_FENV" || exit
        curl -L -O "$RF"/"$FENV"
        popd || exit
        echo "apk succesfully upgraded it self"
        echo "If something is wrong, command <apk restore-apk> to downgrade it to previous version."
        ;;
    restore-apk)
        echo "Restoring apk to previous version"
        cat "$_APK".back > "$_APK" || exit
        cat "$_FENV".back > "$_FENV" || exit
        echo "Success. apk restored to previous version. Please run <apk update> and report a bug if needed: $MAIN_REPO/issues"
        ;;
    *)
        echo "Unknown command: $command"
        exit 1
        ;;
esac
fi
